parameters:
  logger.name:      'daemon'
  logger.file_path: 'var/daemon.log'
  pid.file_path:    'var/daemon.pid'
  config.file_path: 'config/server/params.yml'

services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  App\:
    resource: '../../src/*'
    exclude: '../src/{Client,DI.php}'

  App\Config\Config:
    class: App\Config\Config
    arguments:
      $sourceFile: '%config.file_path%'

  App\Server\Daemon\PidManager:
    class: App\Server\Daemon\PidManager
    arguments:
      $pidFile: '%pid.file_path%'

  App\Repository\Base62RepositoryInterface:
    class: App\Server\Repository\Base62LocalRepository

  App\Server\Daemon\Runnable\RunnableInterface:
    class: App\Server\Daemon\Runnable\SocketRunnable

  Amirax\Base62:
    class: Amirax\Base62

  Psr\Log\LoggerInterface:
    factory:   'App\Factory\LoggerFactory:create'
    arguments: ['%logger.file_path%', '%logger.name%']